"":
  joint_states_controller:
      type: joint_state_controller/JointStateController
      publish_rate: 25

  joint_group_position_controller:
      type: effort_controllers/JointTrajectoryController
      joints:
          - shoulder_joint_lf
          - elbow_joint_lf
          - knee_joint_lf
          - shoulder_joint_rf
          - elbow_joint_rf
          - knee_joint_rf
          - shoulder_joint_lb
          - elbow_joint_lb
          - knee_joint_lb
          - shoulder_joint_rb
          - elbow_joint_rb
          - knee_joint_rb

      gains:
        shoulder_joint_lf        : {p: 180, d: 0.9, i: 20}
        elbow_joint_lf           : {p: 180, d: 0.9, i: 20}
        knee_joint_lf            : {p: 180, d: 0.9, i: 20}
        shoulder_joint_rf        : {p: 180, d: 0.9, i: 20}
        elbow_joint_rf           : {p: 180, d: 0.9, i: 20}
        knee_joint_rf            : {p: 180, d: 0.9, i: 20}
        shoulder_joint_lb        : {p: 180, d: 0.9, i: 20}
        elbow_joint_lb           : {p: 180, d: 0.9, i: 20}
        knee_joint_lb            : {p: 180, d: 0.9, i: 20}
        shoulder_joint_rb        : {p: 180, d: 0.9, i: 20}
        elbow_joint_rb           : {p: 180, d: 0.9, i: 20}
        knee_joint_rb            : {p: 180, d: 0.9, i: 20}
